package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"kns_server/graph/generated"
	"kns_server/graph/model"
)

// Media is the resolver for the media field.
func (r *facebookAttachmentResolver) Media(ctx context.Context, obj *model.FacebookAttachment) (*model.FacebookMedia, error) {
	panic(fmt.Errorf("not implemented: Media - media"))
}

// Target is the resolver for the target field.
func (r *facebookAttachmentResolver) Target(ctx context.Context, obj *model.FacebookAttachment) (*model.FacebookTarget, error) {
	panic(fmt.Errorf("not implemented: Target - target"))
}

// Attachments is the resolver for the attachments field.
func (r *facebookPostResolver) Attachments(ctx context.Context, obj *model.FacebookPost) ([]*model.FacebookAttachment, error) {
	panic(fmt.Errorf("not implemented: Attachments - attachments"))
}

// Facebook is the resolver for the facebook field.
func (r *queryResolver) Facebook(ctx context.Context) (*model.FacebookData, error) {
	data := model.Facebook()

	return &model.FacebookData{
		ID: data.ID,
		Posts: &model.FacebookPosts{
			Data:   data.Posts.Data,
			Paging: data.Posts.Paging,
		},
	}, nil
}

// FacebookAttachment returns generated.FacebookAttachmentResolver implementation.
func (r *Resolver) FacebookAttachment() generated.FacebookAttachmentResolver {
	return &facebookAttachmentResolver{r}
}

// FacebookPost returns generated.FacebookPostResolver implementation.
func (r *Resolver) FacebookPost() generated.FacebookPostResolver { return &facebookPostResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type facebookAttachmentResolver struct{ *Resolver }
type facebookPostResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *facebookCommentsResolver) Comments(ctx context.Context, obj *model.FacebookComments) (*model.FacebookComments, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}

type facebookCommentsResolver struct{ *Resolver }
