// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FacebookImage struct {
	Height *int    `json:"height"`
	Src    *string `json:"src"`
	Width  *int    `json:"width"`
}

type FacebookMedia struct {
	Image *FacebookImage `json:"image"`
}

type FacebookTarget struct {
	ID  *string `json:"id"`
	URL *string `json:"url"`
}
